name: Build Windows Go Executables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Go Programs
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Change to your desired Go version

      - name: Remove Stale Builds
        run: |
          del Shaman.exe
          del ShamanCLI.exe

      - name: Build DEBUG Client (CLI)
        run: |
          cd package
          set GOARCH=amd64
          go build -o ../ShamanCLI.exe -ldflags="-w -s"

      - name: Build PRODUCTION Client (GUI)
        run: |
          cd package
          set GOARCH=amd64
          go build -o ../Shaman.exe -ldflags="-w -s -H=windowsgui"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shaman-windows-builds
          path: |
            Shaman.exe
            ShamanCLI.exe
            
